common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'
urlpatterns = [
     #서치뷰
     path('', base_views.SearchFormView.as_view(), name='search'),
    # base_views.py
     # path('',
     #       base_views.index, name='index'),
    path('<int:answer_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/',
         comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/',
         comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/',
         comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/',
         comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/',
         comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/',
         comment_views.comment_delete_answer, name='comment_delete_answer'),
]

pybo/views/base_views.py
# ---------------------------------- [edit] ---------------------------------- #
from django.shortcuts import render, get_object_or_404, redirect
# ---------------------------------------------------------------------------- #
from ..models import Question, Answer, Comment,Header_home
from django.utils import timezone
from ..forms import QuestionForm, AnswerForm, CommentForm, PostSearchForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django import forms
from django.views.generic import FormView
from django.db.models import Q
""" 서치바 기능 도입중 """

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'search_index.html'
    
    

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Answer.objects.filter(Q(content__icontains=searchWord) | Q(subject__icontains=searchWord)).distinct()
        question_list = Question.objects.order_by('create_date')
        answer_list = Answer.objects.order_by('create_date')

        context = {}
        
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list
        context['question_list'] = question_list
        context['answer_list'] = answer_list
        
        
        return render(self.request, self.template_name, context)


def index(request):
    """
    pybo 목록 출력
    """
     # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
        # 조회
    question_list = Question.objects.order_by('create_date')
    answer_list = Answer.objects.order_by('create_date')
    search_url = 'pybo/'
    header_home = Header_home.objects.get(pk=1)

    context = {'question_list': question_list,'answer_list': answer_list,'search_url': search_url,'header_home': header_home}
    return render(request, 'index.html', context)
# ---------------------------------------------------------------------------- #    
def detail(request, answer_id):
    """
    pybo 내용 출력
    """
    
    question_list = Question.objects.order_by('create_date')
    answer_list = Answer.objects.order_by('create_date')
    search_url = '../'
    

    answer = get_object_or_404(Answer, pk=answer_id)
    context = {'answer': answer, 'question_list': question_list,'answer_list': answer_list,'search_url': search_url}
    return render(request, 'index.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'base_style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<script src="{% static 'base.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                 {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
    {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/search.html
<div class="input-group icons">   
           
        <form  action="{% url 'pybo:search' %}" method="post" id="search" >
            {% csrf_token %}
            <div class="input-group-prepend">
                <span onclick="document.getElementById('search').submit();" style="cursor:pointer;" class="input-group-text bg-transparent border-0 pr-2 pr-sm-3" id="basic-addon1"><i class="mdi mdi-magnify"></i></span>
                <input type="text"name="search_word" class="form-control">
            
            </div>
            
        </form>
        
</div>